<section class="has-actions style-default-bright">

    <!-- BEGIN INBOX -->
    <div class="section-body">
        <div class="row">
            <!-- BEGIN INBOX NAV -->
            <div class="col-sm-4 col-md-3 col-lg-2 hidden-xs">

            </div><!--end . -->
            <!-- END INBOX NAV -->

            <!-- BEGIN MAIL COMPOSE -->
            <div class="col-sm-8 col-md-9 col-lg-10">
                <h3>Compose</h3>
                <form method="POST" name="Resources" id="Manager" class="form&#x20;floating-label&#x20;form-validate" accept-charset="utf-8" role="form" action="action-form-do-formulario">


                    <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8">
                        <fieldset>
                            <legend>GERAL</legend>
                            #id#
                            #asset_id#
                            #codigo#
                            #empresa#
                            <div class="row"><div class="col-md-12"><div class="form-group">#title#{{title}}</div></div></div>
                            <div class="row"><div class="col-md-12"><div class="form-group">#alias#{{alias}}</div></div></div>
                            <div class="row"><div class="col-md-12"><div class="form-group">#description#{{description}}</div></div></div>
                            #security#

                            <div class="clearfix"></div>
                        </fieldset>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                        <fieldset>
                            <legend>FORMULARIO DE ADICIONAL</legend>
                            <div class="row">
                                <div class="col-md-12">

                                    <div class="clearfix"></div>
                                </div>
                                <div class="col-md-12">
                                    <div class="row"><div class="col-md-12"><div class="form-group">#access#{{access}}</div></div></div>
                                    <div class="row"><div class="col-md-12"><div class="form-group">#state#{{state}}</div></div></div>
                                    <div class="row"><div class="col-md-12"><div class="form-group">
                                                <div class="input-group date" id="demo-date">
                                                    <div class="input-group-content">
                                                        #created#
                                                        {{created}}

                                                    </div>
                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                </div>
                                            </div>
                                        </div></div>
                                    #modified#
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </fieldset>
                    </div>


                    <div class="clearfix"></div>

                    <!-- BEGIN SECTION ACTION -->
                    <div class="section-action style-primary">
                        <div class="section-action-row">
                         </div>
                        <div class="section-floating-action-row">
                            #btn-voltar#
                            #comando#

                        </div>
                    </div>
                </form>
                <!-- END INBOX -->
              <!-- END SECTION ACTION -->
</section>