 <div class="main main-raised" style="margin-top: 40px">
        <div class="container">
       <div class="row">
    <div class="col-md-12">
        
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron" style="text-align: center">
                <h1><i class="fa fa-frown-o fa-5x" aria-hidden="true"></i></h1>
                <p>OH NO!, Não foi possivel completar a sua requisição, talvez voçê não tenha permissão!</p>
                <div class="col-md-6 col-xs-12 col-xs-offset-0 col-md-offset-3">
                   <?php if($this->UserIdentity()->getHasIdentity()):?>
                    <a href="<?=$this->url('admin')?>" class="btn btn-danger btn-block btn-lg">IR PARA O ADMIN!</a>
                <?php else:?>
                  <a href="<?=$this->url('auth/default',['controller'=>'auth','action'=>'login'])?>" class="btn btn-danger btn-block btn-lg">IR PARA TELA DE LOGIN!</a>
                   <?php endif;?>
                </div>
                
                <div class="clearfix"></div>
            </div>

        </div>

    </div>

    </div>
</div>
</div>
</div>