<!-- BEGIN LOGIN SECTION -->
<section class="section-account">
    <div class="img-backdrop" style="background-image: url('/materialize_admin/assets/img/img16.png')"></div>
    <div class="spacer"></div>
    <div class="card contain-sm style-transparent">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 col-xs-12 col-md-offset-3 col-xs-offset-0">
                    <br/>
                    <span class="text-lg text-bold text-primary">MATERIAL PROMAGA REUNIÃO</span>
                    <br/><br/>
                    <?php $partial=$this->partial("/auth/auth/tpl/login-tpl");
                    $form->setAttribute('action',$this->url('authenticate'));?>
                    <?=$this->UserIdentity()->getForm($partial,$form);?>
                </div><!--end .col -->
                
            </div><!--end .row -->
        </div><!--end .card-body -->
    </div><!--end .card -->
</section>
<!-- END LOGIN SECTION -->