<!-- BEGIN LOCKED SECTION -->
        <section class="section-account">
            <div class="img-backdrop" style="background-image: url('/materialize_admin/assets/img/img16.png')"></div>
            <div class="spacer"></div>
            <div class="card contain-xs style-transparent">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <img class="img-circle" src="/dist/<?php echo $this->UserIdentity()->getHasIdentity()->images ?>" alt="" />
                            <h2><?php echo $this->UserIdentity()->getHasIdentity()->title ?></h2>
                            <?php $partial=$this->partial("/auth/auth/tpl/update-password");
                            $form->setAttribute('action',$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'update-password']));?>
                            <?=$this->UserIdentity()->getForm($partial,$form);?>
                        </div><!--end .col -->
                    </div><!--end .row -->
                </div><!--end .card-body -->
            </div><!--end .card -->
        </section>
        <!-- END LOCKED SECTION -->