        <div class="header header-filter" style="background-image: url('/materialize_home/assets/img/examples/city.jpg');"></div>

        <div class="main main-raised">
            <div class="profile-content">
                <div class="container">
                    <div class="row">
                        <div class="profile">
                            <div class="avatar">
                                <img id="img-preview" src="/dist/<?php echo $this->UserIdentity()->getHasIdentity()->images ?>" alt="Circle Image" class="img-circle img-responsive img-raised">

                            </div>
                            <div class="name">
                                <h3 class="title"><?php echo $this->UserIdentity()->getHasIdentity()->title ?></h3>
                                <h6> Designer</h6>
                            </div>
                        </div>
                    </div>
                    <div class="description text-center">
                        <p><?php echo $this->UserIdentity()->getHasIdentity()->description ?> </p>
                    </div>

                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            
                        <?php echo $this->messages(); ?>
                        <?php $partial=$this->partial("/auth/auth/tpl/profile");
                        $form->setAttribute('action',$this->url("{$this->route}/default",['controller'=>$this->controller,'action'=>'update-profile']));?>
                        <?=$this->UserIdentity()->getForm($partial,$form);?>
                        <hr>
                        <p class="p-separator">
                            <a  href="<?php echo $this->url("home") ?>">&larrhk; Voltar para Site!</a> &nbsp;&nbsp;&nbsp;
                            <a  href="<?=$this->url("admin");?>"><?php echo $this->translate('Voltar Para Administração &#8618;'); ?></a>
                        </p>
                            <!-- End Profile Tabs -->
                        </div>
                    </div>

                </div>
            </div>
        </div>