<div class="form-group">
    #security#     #email#
    {{email}}
</div>
<br>
<div class="row">
    <div class="col-xs-12 text-right">
        #save#
    </div><!--end .col -->
</div><!--end .row -->
<br>
<div class="row">
    <div class="col-xs-12 col-md-6">
        <p class="help-block">
            <a  href="<?php echo $this->url("home") ?>">&larrhk; Voltar para Site!</a>
        </p>
    </div>
    <div class="col-xs-12 col-md-6">
        <p class="help-block">
            <a href="<?=$this->url("auth");?>"><?php echo $this->translate('&larrhk;  Voltar P/ Login'); ?></a>
        </p>
    </div>
</div>