#id#
<div class="row">
    <div class="col-xs-12">
        <fieldset>
            <legend>ATUALIZAR SUA SENHA!</legend>
            #security#
            <div class="form-group  has-feedback">
                #password#
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="form-group  has-feedback">
                #usr_password_confirm#
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    #save#
                </div><!-- /.col -->
            </div>
            <div class="clearfix"></div>
              </fieldset>
        </div>
    </div>